### ISSUE TITLE
unit tests are failing after cloning

### ISSUE THREAD

**Issue by fabien-marty** [ztrue/tracerr#12]
### Steps to reproduce:

- clone the repo on a clean box (in a random directory)
- execute `make test`

### Expected result

- tests pass

### Results:

```
=== RUN   TestError
    error_test.go:181: cases[2].Error.StackTrace()[0].Path = "/Users/fab/src/tracerr/error_test.go"; want to has suffix "/src/github.com/ztrue/tracerr/error_test.go"
    [...]
```

note: 
- `/Users/fab/src/tracerr` is my cloning path

but it's compared to `/src/github.com/ztrue/tracerr`

**Comment by ztrue** [comment]
@fabien-marty thank you for taking your time to report the issue.
I merged the fix into the `master` https://github.com/ztrue/tracerr/pull/13
Please update from `master` and give it another try.

**Comment by fabien-marty** [comment]
(sorry for the delay) it works perfectly now!

many thanks

=> I close this
