### ISSUE TITLE
matching api of https://github.com/pkg/errors

### ISSUE THREAD

**Issue by abduld** [ztrue/tracerr#6]
would it be possible to add some missing functions like wrapf and errorf to match the interface of https://github.com/pkg/errors . then this can be a drop in replacement to that package.

thanks

**Comment by ztrue** [comment]
Hi @abduld 
`Errorf` already exists in `tracerr` and it works the same way as `fmt.Errorf`.
There is no `Wrapf`, since `tracerr` does not override the original error message. If one needs to override the error message, then probably `Errorf` should be used.
What is your use case?

**Comment by abduld** [comment]
i'd like to just change the import path and get your line information feature without making modification to the code

**Comment by ztrue** [comment]
I see. Sorry, but it's not possible since `tracerr.Wrapf` would have the redundant first argument. Also, it would be inconsistent with `tracerr.Wrap`.

**Comment by abduld** [comment]
ok thanks. nice project though
